# Echelon form

### 1.	Write a python program to accept a 2 x 2 matrix from the user and convert it to row echelon form.
### 2.	Write a python program to accept a 3 x 3 matrix from the user and convert it to row echelon form.
### 3.	Write a python program to accept a 3 x 4 matrix from the user and convert it to row echelon form.
### 4.	Write a python program to accept an R x C matrix from the user and convert it to echelon form.

In [1]:
import numpy as np
from math import isclose

def echelon_form(mat, pivots=False):
    mat = np.array(mat, dtype=float)
    r, c = mat.shape
    pivot_set = set()
    shift = 0
    
    for i in range(min(r, c)):
        while i+shift<c and all(isclose(elem, 0, abs_tol=1e-08)
                                for elem in mat[i:, i+shift]): shift += 1
        if i+shift==c: break
        
        pivot = mat[i, i+shift]
        for next_row in range(i+1, r):
            below_pivot = mat[next_row, i+shift]
            if not isclose(below_pivot, 0, abs_tol=1e-08):
                if not isclose(pivot, 0, abs_tol=1e-08):
                    mat[next_row] -= (below_pivot/pivot)*mat[i]
                else:
                    mat[[i, next_row]] = mat[[next_row, i]]
                    pivot = below_pivot
        
        pivot_set.add(i+shift)
        mat[i, :i+shift] = 0.
    
    if pivots:
        return mat, pivot_set
    return mat

In [2]:
def input_mat(square=False, dtype=float):
    if square:
        r = c = int(input('Enter the dimension of the square matrix: '))
    else:
        r = int(input('Enter the number of rows: '))
        c = int(input('Enter the number of columns: '))
    
    ret_mat = []
    for i in range(r):
        ret_row = [dtype(input(f'Enter element for position [{i+1}, {j+1}]: ')) for j in range(c)]
        ret_mat.append(ret_row)
    
    return ret_mat

A = input_mat()
print('Matrix A:', A)

print('Echelon form A:\n', echelon_form(A))
print('Echelon form A, with pivot columns:\n', echelon_form(A, pivots=True))

Matrix A: [[1.0, 2.0, 3.0, 4.0, 5.0], [6.0, 7.0, 8.0, 9.0, 0.0], [1.0, 2.0, 3.0, 4.0, 5.0], [6.0, 7.0, 8.0, 9.0, 0.0]]
Echelon form A:
 [[  1.   2.   3.   4.   5.]
 [  0.  -5. -10. -15. -30.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Echelon form A, with pivot columns:
 (array([[  1.,   2.,   3.,   4.,   5.],
       [  0.,  -5., -10., -15., -30.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.]]), {0, 1})


### 5.	Write a python program to accept a 2 x 2 matrix from the user and find the rank of the matrix.
### 6.	Write a python program to accept a 3 x 3 matrix from the user and find the rank of the matrix.
### 7.	Write a python program to accept a 3 x 4 matrix from the user and find the rank of the matrix.
### 8.	Write a python program to accept an R x C matrix from the user and find the rank of the matrix.

In [3]:
import numpy as np
from math import isclose

def echelon_form(mat, pivots=False):
    mat = np.array(mat, dtype=float)
    r, c = mat.shape
    pivot_set = set()
    shift = 0
    
    for i in range(min(r, c)):
        while i+shift<c and all(isclose(elem, 0, abs_tol=1e-08)
                                for elem in mat[i:, i+shift]): shift += 1
        if i+shift==c: break
        
        pivot = mat[i, i+shift]
        for next_row in range(i+1, r):
            below_pivot = mat[next_row, i+shift]
            if not isclose(below_pivot, 0, abs_tol=1e-08):
                if not isclose(pivot, 0, abs_tol=1e-08):
                    mat[next_row] -= (below_pivot/pivot)*mat[i]
                else:
                    mat[[i, next_row]] = mat[[next_row, i]]
                    pivot = below_pivot
        
        pivot_set.add(i+shift)
        mat[i, :i+shift] = 0.
    
    if pivots:
        return mat, pivot_set
    return mat

def rank(mat):
    mat, pivots = echelon_form(mat, pivots=True)
    
    return len(pivots)

In [6]:
def input_mat(square=False, dtype=float):
    if square:
        r = c = int(input('Enter the dimension of the square matrix: '))
    else:
        r = int(input('Enter the number of rows: '))
        c = int(input('Enter the number of columns: '))
    
    ret_mat = []
    for i in range(r):
        ret_row = [dtype(input(f'Enter element for position [{i+1}, {j+1}]: ')) for j in range(c)]
        ret_mat.append(ret_row)
    
    return ret_mat

A = input_mat()
print('Matrix A:', A)

print('Rank A:', rank(A))

Matrix A: [[1.0, 2.0, 3.0, 4.0, 5.0], [6.0, 7.0, 8.0, 9.0, 0.0], [1.0, 2.0, 3.0, 4.0, 5.0], [6.0, 7.0, 8.0, 9.0, 0.0]]
Rank A: 2
